### ISSUE TITLE
Live Alt Az from SkyX

### ISSUE THREAD

**Issue by Bhavesh012** [albertw/pyskyx#1]
Hey! I have a Paramount ME mount which I control through SkyX Pro. Is there a way/command to get the live alt az or ra dec of the object which my mount is tracking? I need those values to send it to my Arduino board for controlling the dome.

**Comment by lmolteno** [comment]
Howdy,
There is no command at the moment, but it would be near identical to ```sky6RASCOMTele.GetRaDec()```.

The definition can be found here: https://github.com/albertw/pyskyx/blob/e449983fd7e3779dc8028b6a50bd5bb0474fdf50/skyx.py#L429-L438

One would need to change the call in the JS to [getAzAlt](https://www.bisque.com/wp-content/scriptthesky/classsky6_r_a_s_c_o_m_tele.html#a7c10501afaf12b4a030fc235df42cab3) and access the output using ```sky6RASCOMTele.dAz``` instead of ```dRa```, so, something along the lines of this being added to the ```sky6RASCOMTele``` class in the ```skyx.py``` file (I haven't tested this, but it should work).

```python
def GetAzAlt(self): 
   ''' Get the current Altitude and Azimuth
   ''' 
   command = """ 
             var Out; 
             sky6RASCOMTele.GetAzAlt(); 
             Out = String(sky6RASCOMTele.dAz) + " " + String(sky6RASCOMTele.dAlt); 
             """ 
   output = self.conn._send(command).splitlines()[0].split()       
   return output 
```

The returned value from this function would be a list/tuple containing the (azimuth, altitude) of the current position of the telescope. One could also use the getRaDec function and do some astropy magic to convert RA-Dec to Alt-Az for the location of the telescope, but given that the SkyX is already doing the math for you, it would probably be best to do it using the JS API as this function does.

However, this might not be the best way to create a dome controller. I would consider trying to work with an ASCOM dome driver, for which there are a few Arduino projects for (such as [this one](https://github.com/juanmb/ArduinoDomeController)), which means that SkyX will do all the calculations for offsets for your scope within the dome for you, and will just send the Arduino the required rotation and shutter raisingness through the ASCOM driver. But, I have no experience with creating/working with ASCOM drivers, and so this option might be easier and require a bit less fiddling. If you didn't want to have to work with an ASCOM driver you might be able to have the SkyX run with a dome simulator, so it still does all the math for the required rotation and shutter raisingness, and then you could extract the numbers in a similar way, using the [sky6Dome](https://www.bisque.com/wp-content/scriptthesky/classsky6_dome.html) object in the JS API. Again, I haven't tested this so it might not work.

Sorry for the wall of text, but feel free to ask if you have any more questions!

**Comment by Bhavesh012** [comment]
Hey man! Thanks a lot for the fast reply. Yes, I agree, working with ASCOM driver would be better. But yeah I will try that snippet and see if it works out for now. Thanks again!
